In [1]:
# SVM Classification 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [2]:
#### SVM Salary (Trai_data)

In [3]:
salary = pd.read_csv("SalaryData_Train(1).csv")
salary.head()

age          workclass   education  educationno        maritalstatus  \
0   39          State-gov   Bachelors           13        Never-married   
1   50   Self-emp-not-inc   Bachelors           13   Married-civ-spouse   
2   38            Private     HS-grad            9             Divorced   
3   53            Private        11th            7   Married-civ-spouse   
4   28            Private   Bachelors           13   Married-civ-spouse   

           occupation    relationship    race      sex  capitalgain  \
0        Adm-clerical   Not-in-family   White     Male         2174   
1     Exec-managerial         Husband   White     Male            0   
2   Handlers-cleaners   Not-in-family   White     Male            0   
3   Handlers-cleaners         Husband   Black     Male            0   
4      Prof-specialty            Wife   Black   Female            0   

   capitalloss  hoursperweek          native  Salary  
0            0            40   United-States   <=50K  
1            0            13   United-States   <=50K  
2            0            40   United-States   <=50K  
3            0            40   United-States   <=50K  
4            0            40            Cuba   <=50K

In [4]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [5]:
salary['workclass']=salary['workclass'].astype('category')
salary['education']=salary['education'].astype('category')
salary['maritalstatus']=salary['maritalstatus'].astype('category')
salary['occupation']=salary['occupation'].astype('category')
salary['relationship']=salary['relationship'].astype('category')
salary['race']=salary['race'].astype('category')
salary['native']=salary['native'].astype('category')
salary['sex']=salary['sex'].astype('category')

In [6]:
salary.dtypes

age                 int64
workclass        category
education        category
educationno         int64
maritalstatus    category
occupation       category
relationship     category
race             category
sex              category
capitalgain         int64
capitalloss         int64
hoursperweek        int64
native           category
Salary             object
dtype: object

In [7]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [8]:
salary['Salary'] = label_encoder.fit_transform(salary['Salary'])

In [9]:
salary.Salary

0        0
1        0
2        0
3        0
4        0
        ..
30156    0
30157    1
30158    0
30159    0
30160    1
Name: Salary, Length: 30161, dtype: int32

In [10]:
salary['workclass'] = label_encoder.fit_transform(salary['workclass'])
salary['education'] = label_encoder.fit_transform(salary['education'])
salary['maritalstatus'] = label_encoder.fit_transform(salary['maritalstatus'])
salary['occupation'] = label_encoder.fit_transform(salary['occupation'])
salary['relationship'] = label_encoder.fit_transform(salary['relationship'])
salary['race'] = label_encoder.fit_transform(salary['race'])
salary['sex'] = label_encoder.fit_transform(salary['sex'])
salary['native'] = label_encoder.fit_transform(salary['native'])

In [11]:
salary

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1         2174            0            40   
1                 0     4    1            0            0            13   
2                 1     4    1            0            0            40   
3                 0     2    1            0            0            40   
4                 5     2    0            0            0            40   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            38   
30157             0     4    1            0            0            40   
30158             4     4    0            0            0            40   
30159             3     4    1            0            0            20   
30160             5     4    0        15024            0            40   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
30156      37       0  
30157      37       1  
30158      37       0  
30159      37       0  
30160      37       1  

[30161 rows x 14 columns]

In [12]:
# spliting the data into x and y as input and output

X = salary.iloc[:,0:13]
Y = salary.iloc[:,13]

In [13]:
X

age  workclass  education  educationno  maritalstatus  occupation  \
0       39          5          9           13              4           0   
1       50          4          9           13              2           3   
2       38          2         11            9              0           5   
3       53          2          1            7              2           5   
4       28          2          9           13              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   27          2          7           12              2          12   
30157   40          2         11            9              2           6   
30158   58          2         11            9              6           0   
30159   22          2         11            9              4           0   
30160   52          3         11            9              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 1     4    1         2174            0            40      37  
1                 0     4    1            0            0            13      37  
2                 1     4    1            0            0            40      37  
3                 0     2    1            0            0            40      37  
4                 5     2    0            0            0            40       4  
...             ...   ...  ...          ...          ...           ...     ...  
30156             5     4    0            0            0            38      37  
30157             0     4    1            0            0            40      37  
30158             4     4    0            0            0            40      37  
30159             3     4    1            0            0            20      37  
30160             5     4    0        15024            0            40      37  

[30161 rows x 13 columns]

In [14]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
30156    0
30157    1
30158    0
30159    0
30160    1
Name: Salary, Length: 30161, dtype: int32

In [15]:
salary.Salary.unique()

array([0, 1])

In [16]:
salary.Salary.value_counts()

0    22653
1     7508
Name: Salary, dtype: int64

In [17]:
# spliting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [18]:
clf=SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 79.23527461597966


array([[6580,  218],
       [1661,  590]], dtype=int64)

In [19]:
y_pred = clf.predict(x_test)

In [20]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
#### SVM Salary (test_data)

In [22]:
salary = pd.read_csv("SalaryData_Test(1).csv (1).crdownload")

In [23]:
salary

age   workclass      education  educationno        maritalstatus  \
0       25     Private           11th            7        Never-married   
1       38     Private        HS-grad            9   Married-civ-spouse   
2       28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44     Private   Some-college           10   Married-civ-spouse   
4       34     Private           10th            6        Never-married   
...    ...         ...            ...          ...                  ...   
12949   58   Local-gov        Masters           14   Married-civ-spouse   
12950   44     Private      Bachelors           13   Married-civ-spouse   
12951   45     Private        Masters           14             Divorced   
12952   27     Private   Some-college           10        Never-married   
12953   51     Private      Assoc-voc           11             Divorced   

               occupation    relationship    race      sex  capitalgain  \
0       Machine-op-inspct       Own-child   Black     Male            0   
1         Farming-fishing         Husband   White     Male            0   
2         Protective-serv         Husband   White     Male            0   
3       Machine-op-inspct         Husband   Black     Male         7688   
4           Other-service   Not-in-family   White     Male            0   
...                   ...             ...     ...      ...          ...   
12949      Prof-specialty         Husband   White     Male            0   
12950     Exec-managerial         Husband   White     Male         7688   
12951      Prof-specialty   Not-in-family   White     Male        27828   
12952   Handlers-cleaners   Not-in-family   White     Male            0   
12953      Prof-specialty   Not-in-family   White   Female            0   

       capitalloss  hoursperweek          native  Salary  
0                0            40   United-States   <=50K  
1                0            50   United-States   <=50K  
2                0            40   United-States    >50K  
3                0            40   United-States    >50K  
4                0            30   United-States   <=50K  
...            ...           ...             ...     ...  
12949            0            40   United-States    >50K  
12950            0            50   United-States    >50K  
12951            0            50   United-States    >50K  
12952            0            38   United-States   <=50K  
12953            0            48               U     NaN  

[12954 rows x 14 columns]

In [24]:
salary.head

<bound method NDFrame.head of        age   workclass      education  educationno        maritalstatus  \
0       25     Private           11th            7        Never-married   
1       38     Private        HS-grad            9   Married-civ-spouse   
2       28   Local-gov     Assoc-acdm           12   Married-civ-spouse   
3       44     Private   Some-college           10   Married-civ-spouse   
4       34     Private           10th            6        Never-married   
...    ...         ...            ...          ...                  ...   
12949   58   Local-gov        Masters           14   Married-civ-spouse   
12950   44     Private      Bachelors           13   Married-civ-spouse   
12951   45     Private        Masters           14             Divorced   
12952   27     Private   Some-college           10        Never-married   
12953   51     Private      Assoc-voc           11             Divorced   

               occupation    relationship    race      sex  capitalga

In [25]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12954 entries, 0 to 12953
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            12954 non-null  int64 
 1   workclass      12954 non-null  object
 2   education      12954 non-null  object
 3   educationno    12954 non-null  int64 
 4   maritalstatus  12954 non-null  object
 5   occupation     12954 non-null  object
 6   relationship   12954 non-null  object
 7   race           12954 non-null  object
 8   sex            12954 non-null  object
 9   capitalgain    12954 non-null  int64 
 10  capitalloss    12954 non-null  int64 
 11  hoursperweek   12954 non-null  int64 
 12  native         12954 non-null  object
 13  Salary         12953 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.4+ MB


In [26]:
salary['workclass']=salary['workclass'].astype('category')
salary['education']=salary['education'].astype('category')
salary['maritalstatus']=salary['maritalstatus'].astype('category')
salary['occupation']=salary['occupation'].astype('category')
salary['relationship']=salary['relationship'].astype('category')
salary['race']=salary['race'].astype('category')
salary['native']=salary['native'].astype('category')
salary['sex']=salary['sex'].astype('category')

In [27]:
salary.dtypes

age                 int64
workclass        category
education        category
educationno         int64
maritalstatus    category
occupation       category
relationship     category
race             category
sex              category
capitalgain         int64
capitalloss         int64
hoursperweek        int64
native           category
Salary             object
dtype: object

In [28]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

In [29]:
salary['Salary'] = label_encoder.fit_transform(salary['Salary'])

In [30]:
salary.Salary

0        0
1        0
2        1
3        1
4        0
        ..
12949    1
12950    1
12951    1
12952    0
12953    2
Name: Salary, Length: 12954, dtype: int32

In [31]:
#we also need to convert categories into numbers
salary['workclass'] = label_encoder.fit_transform(salary['workclass'])
salary['education'] = label_encoder.fit_transform(salary['education'])
salary['maritalstatus'] = label_encoder.fit_transform(salary['maritalstatus'])
salary['occupation'] = label_encoder.fit_transform(salary['occupation'])
salary['relationship'] = label_encoder.fit_transform(salary['relationship'])
salary['race'] = label_encoder.fit_transform(salary['race'])
salary['sex'] = label_encoder.fit_transform(salary['sex'])
salary['native'] = label_encoder.fit_transform(salary['native'])

In [32]:
salary

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
12949   58          1         12           14              2           9   
12950   44          2          9           13              2           3   
12951   45          2         12           14              0           9   
12952   27          2         15           10              4           5   
12953   51          2          8           11              0           9   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            40   
1                 0     4    1            0            0            50   
2                 0     4    1            0            0            40   
3                 0     2    1         7688            0            40   
4                 1     4    1            0            0            30   
...             ...   ...  ...          ...          ...           ...   
12949             0     4    1            0            0            40   
12950             0     4    1         7688            0            50   
12951             1     4    1        27828            0            50   
12952             1     4    1            0            0            38   
12953             1     4    0            0            0            48   

       native  Salary  
0          38       0  
1          38       0  
2          38       1  
3          38       1  
4          38       0  
...       ...     ...  
12949      38       1  
12950      38       1  
12951      38       1  
12952      38       0  
12953      37       2  

[12954 rows x 14 columns]

In [33]:
# define x & y

X = salary.iloc[:,0:13]
Y = salary.iloc[:,13]

In [34]:
X

age  workclass  education  educationno  maritalstatus  occupation  \
0       25          2          1            7              4           6   
1       38          2         11            9              2           4   
2       28          1          7           12              2          10   
3       44          2         15           10              2           6   
4       34          2          0            6              4           7   
...    ...        ...        ...          ...            ...         ...   
12949   58          1         12           14              2           9   
12950   44          2          9           13              2           3   
12951   45          2         12           14              0           9   
12952   27          2         15           10              4           5   
12953   51          2          8           11              0           9   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  native  
0                 3     2    1            0            0            40      38  
1                 0     4    1            0            0            50      38  
2                 0     4    1            0            0            40      38  
3                 0     2    1         7688            0            40      38  
4                 1     4    1            0            0            30      38  
...             ...   ...  ...          ...          ...           ...     ...  
12949             0     4    1            0            0            40      38  
12950             0     4    1         7688            0            50      38  
12951             1     4    1        27828            0            50      38  
12952             1     4    1            0            0            38      38  
12953             1     4    0            0            0            48      37  

[12954 rows x 13 columns]

In [35]:
Y

0        0
1        0
2        1
3        1
4        0
        ..
12949    1
12950    1
12951    1
12952    0
12953    2
Name: Salary, Length: 12954, dtype: int32

In [36]:
salary.Salary.unique()

array([0, 1, 2])

In [37]:
salary.Salary.value_counts()

0    9762
1    3191
2       1
Name: Salary, dtype: int64

In [38]:
# spliting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(X,Y, test_size=0.3, random_state=0)

In [39]:
# model building by using SVm
clf = SVC()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
acc = accuracy_score(y_test, y_pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, y_pred)

Accuracy = 79.28994082840237


array([[2812,  115,    0],
       [ 689,  270,    0],
       [   1,    0,    0]], dtype=int64)

In [40]:
y_pred = clf.predict(x_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0])